name: "next-version-proposal-action"
description: "Github action which recommends a name for the next version based on your git tag and pull request labels"
author: "bbonkr"
branding:
  color: purple
  icon: check
inputs:
  github_token:
    required: false
    description: "GitHub Personal Access Token. It requires REPO scope."
    default: ${{ github.token }}
  pr:
    required: false
    description: "Pull request number. Input just number. e.g.) 100"
    default: ${{ github.event.pull_request.number }}
  owner:
    required: false
    description: "Name of repository owner, For test. You does not need this input."
    default: ""
  repo:
    required: false
    description: "Repository name; For test. You does not need this input."
    default: ""
  major_labels:
    required: false
    description: "A comma-separated list of label names to increment the major version by."
    default: "major,next"
  minor_labels:
    required: false
    description: "A comma-separated list of label names to increment the minor version by."
    default: "enhancement,feature"
  next_version_prefix:
    required: false
    description: "Next version prefix"
    default: ""
  logging:
    required: false
    description: "Shows logging message (Please set true if you want to show logging messages)"
    default: ""

outputs:
  latest_version:
    description: "Latest version of git tag"
  next_version:
    description: "Recommended next version name"
  next_version_major:
    description: "Major version of Recommended next version"
  next_version_minor:
    description: "Minor version of Recommended next version"
  next_version_patch:
    description: "Patch version of Recommended next version"
runs:
  using: "node20"
  main: "dist/index.js"
