name: "create-tag"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  NODE_VERSION: 20.x

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    steps:
      - uses: actions/checkout@v4

      - name: "Set Node.js ${{ env.NODE_VERSION }}"
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Install dependencies
        run: |
          npm install

      - name: Run npm all script
        run: |
          npm run all
        # env:
        #   NODE_ENV: 'production'

      - name: Logging github.ref
        run: |
          echo "github.ref=${{ github.ref }}"  
          echo "github.event.pull_request.number=${{ github.event.pull_request.number }}"
          echo "github.event.pull_request.base.ref=${{ github.event.pull_request.base.ref }}"
          echo "github.event.pull_request.head.ref=${{ github.event.pull_request.head.ref }}"

      - name: Get next version
        uses: ./
        id: next_version_proposal
        with:
          next_version_prefix: "v"
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}

      - name: logging next_version_proposal
        run: |
          echo "latest_version=${{ steps.next_version_proposal.outputs.latest_version }}"
          echo "next_version=${{ steps.next_version_proposal.outputs.next_version }}"
          echo "next_version_major=${{ steps.next_version_proposal.outputs.next_version_major }}"
          echo "next_version_minor=${{ steps.next_version_proposal.outputs.next_version_minor }}"
          echo "next_version_patch=${{ steps.next_version_proposal.outputs.next_version_patch }}"

      - name: Create or update tag major
        uses: rickstaa/action-create-tag@v1
        if: ${{ (steps.next_version_proposal.outputs.next_version != '') && (steps.next_version_proposal.outputs.next_version_major != '') }}
        with:
          tag: "v${{ steps.next_version_proposal.outputs.next_version_major }}"
          message: "Overwrite v${{ steps.next_version_proposal.outputs.next_version_major }}"
          commit_sha: ${{ github.sha }}
          force_push_tag: true

      - name: Create or update tag major.minor
        uses: rickstaa/action-create-tag@v1
        if: ${{ (steps.next_version_proposal.outputs.next_version != '') && (steps.next_version_proposal.outputs.next_version_major != '') && (steps.next_version_proposal.outputs.next_version_minor != '') }}
        with:
          tag: "v${{ steps.next_version_proposal.outputs.next_version_major }}.${{ steps.next_version_proposal.outputs.next_version_minor }}"
          message: "Overwrite v${{ steps.next_version_proposal.outputs.next_version_major }}.${{ steps.next_version_proposal.outputs.next_version_minor }}"
          commit_sha: ${{ github.sha }}
          force_push_tag: true

      - name: Create tag current
        uses: rickstaa/action-create-tag@v1
        if: ${{ steps.next_version_proposal.outputs.next_version != '' }}
        with:
          tag: "${{ steps.next_version_proposal.outputs.next_version }}"
          message: "New release ${{ steps.next_version_proposal.outputs.next_version }}"
          commit_sha: ${{ github.sha }}

      - name: create GitHub Release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        if: ${{ steps.next_version_proposal.outputs.next_version != '' }}
        with:
          config-name: release-drafter.yml
          version: ${{ steps.next_version_proposal.outputs.next_version }}
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: git tag skipped
        if: ${{ steps.next_version_proposal.outputs.next_version == '' }}
        run: |
          echo "Next version tag is empty."
